name: Deploy to QA

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Copy files to QA instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.QA_INSTANCE_IP }} 'mkdir -p /var/www/html'
        scp -o StrictHostKeyChecking=no -r * ubuntu@${{ secrets.QA_INSTANCE_IP }}:/var/www/html

    - name: Restart Nginx on QA instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.QA_INSTANCE_IP }} 'sudo systemctl restart nginx'
