name: CI/CD Workflow

on:
  push:
    branches:
      - test
      - qa
  pull_request:
    branches:
      - main

jobs:
  deploy-to-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    env:
      QA_IP: ${{ secrets.QA_INSTANCE_IP }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to QA instance
        run: |
          echo "Deploying to QA instance..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$QA_IP << 'EOF'
          sudo bash -c 'cat > /var/www/html/index.html <<EOT
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hola Mundo</title>
          </head>
          <body>
              <h1>Hola Mundo en QA</h1>
          </body>
          </html>
          EOT'
          EOF

  deploy-to-production:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      PROD_1_IP: ${{ secrets.PROD_INSTANCE_1_IP }}
      PROD_2_IP: ${{ secrets.PROD_INSTANCE_2_IP }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Instance 1
        run: |
          echo "Deploying to Production Instance 1..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$PROD_1_IP << 'EOF'
          sudo bash -c 'cat > /var/www/html/index.html <<EOT
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hola Mundo</title>
          </head>
          <body>
              <h1>Hola Mundo en PROD (Instancia 1)</h1>
          </body>
          </html>
          EOT'
          EOF

      - name: Deploy to Production Instance 2
        run: |
          echo "Deploying to Production Instance 2..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$PROD_2_IP << 'EOF'
          sudo bash -c 'cat > /var/www/html/index.html <<EOT
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hola Mundo</title>
          </head>
          <body>
              <h1>Hola Mundo en PROD (Instancia 2)</h1>
          </body>
          </html>
          EOT'
          EOF

