name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Copy files to Production instances
      run: |
        # Desplegar en cada una de las 4 instancias de producción
        for INSTANCE in ${{ secrets.INSTANCE_1_IP }} ${{ secrets.INSTANCE_2_IP }} ${{ secrets.INSTANCE_3_IP }} ${{ secrets.INSTANCE_4_IP }}
        do
          ssh -o StrictHostKeyChecking=no ubuntu@$INSTANCE 'mkdir -p /var/www/html'
          scp -o StrictHostKeyChecking=no -r * ubuntu@$INSTANCE:/var/www/html
        done

    - name: Restart Nginx on Production instances
      run: |
        # Reiniciar Nginx en cada instancia
        for INSTANCE in ${{ secrets.INSTANCE_1_IP }} ${{ secrets.INSTANCE_2_IP }} ${{ secrets.INSTANCE_3_IP }} ${{ secrets.INSTANCE_4_IP }}
        do
          ssh -o StrictHostKeyChecking=no ubuntu@$INSTANCE 'sudo systemctl restart nginx'
        done
