name: CI/CD Workflow

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - main

jobs:
  deploy-to-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    env:
      QA_IP: ${{ secrets.QA_INSTANCE_IP }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to QA instance
        run: |
          echo "Deploying to QA instance..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$QA_IP 'sudo mkdir -p /var/www/html && echo "Hola Mundo en QA" | sudo tee /var/www/html/index.html'

  deploy-to-production:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      PROD_1_IP: ${{ secrets.PROD_INSTANCE_1_IP }}
      PROD_2_IP: ${{ secrets.PROD_INSTANCE_2_IP }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Instance 1
        run: |
          echo "Deploying to Production Instance 1..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$PROD_1_IP 'sudo mkdir -p /var/www/html && echo "Hola Mundo en PROD" | sudo tee /var/www/html/index.html'

      - name: Deploy to Production Instance 2
        run: |
          echo "Deploying to Production Instance 2..."
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$PROD_2_IP 'sudo mkdir -p /var/www/html && echo "Hola Mundo en PROD" | sudo tee /var/www/html/index.html'
